name: CI
on:
  push:
  pull_request:

jobs:
  go:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'
          cache: true

      - name: Verify modules
        run: go mod download

      - name: Vet
        run: go vet ./...

      - name: Test (race + coverage)
        run: |
          go test ./... -race -coverprofile=coverage.out -covermode=atomic
          go tool cover -func=coverage.out | tail -n +1
