name: CI
permissions:
  contents: read
on: [push, pull_request, workflow_dispatch]

jobs:
  go:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: Backend   
    steps:
      - uses: actions/checkout@v5

      - uses: actions/setup-go@v6
        with:
          go-version: '1.22'
          cache: true

      - name: Verify modules
        run: |
          go env GOPATH GOMOD
          go mod tidy
          git diff --exit-code || (echo "::error ::run 'go mod tidy' locally and commit changes" && exit 1)
          go mod download

      - name: Vet
        run: go vet ./...

      - name: Test (race + coverage)
        run: |
          go test ./... -race -coverprofile=coverage.out -covermode=atomic
          go tool cover -func=coverage.out | tail -n +1

      - name: Build
        run: go build ./cmd/api

  frontend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: Frontend/slc-frontend
    steps:
      - uses: actions/checkout@v5

      - uses: actions/setup-node@v6
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: Frontend/slc-frontend/package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: Test
        run: npm test

      - name: Build
        run: npm run build
